# Generated by Django 5.1.2 on 2024-10-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=45)),
                ('code_presentation', models.CharField(max_length=45)),
                ('id_assessment', models.IntegerField()),
                ('assessment_type', models.CharField(max_length=45)),
                ('date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=45)),
                ('code_presentation', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('id_assessment', models.IntegerField()),
                ('date_submitted', models.IntegerField()),
                ('is_banked', models.BooleanField(default=False)),
                ('score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=45)),
                ('code_presentation', models.CharField(max_length=45)),
                ('id_student', models.IntegerField()),
                ('gender', models.CharField(max_length=3)),
                ('imd_band', models.CharField(max_length=16, null=True)),
                ('highest_education', models.CharField(max_length=45, null=True)),
                ('age_band', models.CharField(max_length=16, null=True)),
                ('num_of_prev_attempts', models.IntegerField(null=True)),
                ('studied_credits', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=45, null=True)),
                ('disability', models.CharField(max_length=3, null=True)),
                ('final_result', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=45)),
                ('code_presentation', models.CharField(max_length=45)),
                ('id_student', models.IntegerField()),
                ('date_registration', models.IntegerField()),
                ('date_unregistration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_site', models.IntegerField()),
                ('code_module', models.CharField(max_length=45)),
                ('code_presentation', models.CharField(max_length=45)),
                ('activity_type', models.CharField(max_length=45)),
                ('week_from', models.IntegerField()),
                ('week_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentVle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_site', models.IntegerField()),
                ('code_module', models.CharField(max_length=45)),
                ('code_presentation', models.CharField(max_length=45)),
                ('date', models.IntegerField()),
                ('sum_click', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.studentinfo')),
            ],
        ),
    ]
